// <auto-generated />
using System;
using Corporativo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Corporativo.Migrations
{
    [DbContext(typeof(CorporativoContext))]
    partial class CorporativoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Corporativo.Models.DetalleReporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("IdReporte");

                    b.ToTable("DETALLE_REPORTE");
                });

            modelBuilder.Entity("Corporativo.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_region");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("api_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("REGIONES");
                });

            modelBuilder.Entity("Corporativo.Models.ReporteMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Año")
                        .HasColumnType("int")
                        .HasColumnName("año");

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_recepcion");

                    b.Property<int>("IdRegion")
                        .HasColumnType("int")
                        .HasColumnName("id_region");

                    b.Property<int>("Mes")
                        .HasColumnType("int")
                        .HasColumnName("mes");

                    b.Property<decimal>("TotalVentas")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total_ventas");

                    b.HasKey("Id");

                    b.HasIndex("IdRegion", "Año", "Mes")
                        .IsUnique()
                        .HasDatabaseName("IX_ReportesMensuales_Region_Año_Mes");

                    b.ToTable("REPORTES_MENSUALES");
                });

            modelBuilder.Entity("Corporativo.Models.DetalleReporte", b =>
                {
                    b.HasOne("Corporativo.Models.ReporteMensual", "ReporteMensual")
                        .WithMany("DetallesReporte")
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReporteMensual");
                });

            modelBuilder.Entity("Corporativo.Models.ReporteMensual", b =>
                {
                    b.HasOne("Corporativo.Models.Region", "Region")
                        .WithMany("ReportesMensuales")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Corporativo.Models.Region", b =>
                {
                    b.Navigation("ReportesMensuales");
                });

            modelBuilder.Entity("Corporativo.Models.ReporteMensual", b =>
                {
                    b.Navigation("DetallesReporte");
                });
#pragma warning restore 612, 618
        }
    }
}
