// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegionalDataBases.Data;

#nullable disable

namespace RegionalDataBases.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251119052318_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegionalDataBases.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("NombreCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("categoria");

                    b.HasKey("IdCategoria");

                    b.ToTable("CATEGORIAS");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdSucursal");

                    b.ToTable("CLIENTES");
                });

            modelBuilder.Entity("RegionalDataBases.Models.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdReporte")
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("PrecioVenta")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_venta");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdReporte");

                    b.ToTable("DETALLE_VENTAS");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_inventario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<int>("Existencia")
                        .HasColumnType("int")
                        .HasColumnName("existencia");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("ultima_actualizacion");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdSucursal");

                    b.ToTable("INVENTARIO");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit")
                        .HasColumnName("activo");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("PRODUCTOS");
                });

            modelBuilder.Entity("RegionalDataBases.Models.ReporteVenta", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime>("FechaRecepcion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_recepcion");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdSucursal")
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    b.Property<decimal>("TotalVentas")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_ventas");

                    b.HasKey("IdReporte");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdSucursal");

                    b.ToTable("REPORTE_VENTA");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sucursal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit")
                        .HasColumnName("activa");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("direccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("telefono");

                    b.HasKey("IdSucursal");

                    b.ToTable("SUCURSALES");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Cliente", b =>
                {
                    b.HasOne("RegionalDataBases.Models.Sucursal", "Sucursal")
                        .WithMany("Clientes")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("RegionalDataBases.Models.DetalleVenta", b =>
                {
                    b.HasOne("RegionalDataBases.Models.Producto", "Producto")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegionalDataBases.Models.ReporteVenta", "ReporteVenta")
                        .WithMany("DetallesVenta")
                        .HasForeignKey("IdReporte")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("ReporteVenta");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Inventario", b =>
                {
                    b.HasOne("RegionalDataBases.Models.Producto", "Producto")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegionalDataBases.Models.Sucursal", "Sucursal")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Producto", b =>
                {
                    b.HasOne("RegionalDataBases.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RegionalDataBases.Models.ReporteVenta", b =>
                {
                    b.HasOne("RegionalDataBases.Models.Cliente", "Cliente")
                        .WithMany("ReportesVenta")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RegionalDataBases.Models.Sucursal", "Sucursal")
                        .WithMany("ReportesVenta")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Cliente", b =>
                {
                    b.Navigation("ReportesVenta");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Producto", b =>
                {
                    b.Navigation("DetallesVenta");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("RegionalDataBases.Models.ReporteVenta", b =>
                {
                    b.Navigation("DetallesVenta");
                });

            modelBuilder.Entity("RegionalDataBases.Models.Sucursal", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Inventarios");

                    b.Navigation("ReportesVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
